# This workflow will test the java package against Sideko's Mock Servers
# Tests will run automatically on a push to `main` or a pull request event

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          # - "1.8"
          - "11"
          - "17"
          - "18"
          - "19"
          - "20"
    steps:
      #----------------------------------------------
      #  -----  checkout & setup java  -----
      #----------------------------------------------
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      #----------------------------------------------
      #  -----  checkout & setup java  -----
      #----------------------------------------------
      - name: test
        run: gradle test
